{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.textbanner",
    "module": "textbanner",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "textbanner-1.0.0.aar",
          "url": "textbanner-1.0.0.aar",
          "size": 45931,
          "sha512": "282dc483141dad887648814ff71d742747a038e36cbf70867fd65893afd6a0506d0f299d39d62cbdc719b25101fe3e48f38570fd94196b06d71fb3516832f835",
          "sha256": "cd7677fe38a8b54193c58a9df99d37f4fa125fe99ef6bb639e31ccf58473fbbb",
          "sha1": "ec14f1dba4778c379c06f18914be49b5d4255d83",
          "md5": "5b569ea7063d90c17d11118acad2fbfe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "textbanner-1.0.0.aar",
          "url": "textbanner-1.0.0.aar",
          "size": 45931,
          "sha512": "282dc483141dad887648814ff71d742747a038e36cbf70867fd65893afd6a0506d0f299d39d62cbdc719b25101fe3e48f38570fd94196b06d71fb3516832f835",
          "sha256": "cd7677fe38a8b54193c58a9df99d37f4fa125fe99ef6bb639e31ccf58473fbbb",
          "sha1": "ec14f1dba4778c379c06f18914be49b5d4255d83",
          "md5": "5b569ea7063d90c17d11118acad2fbfe"
        }
      ]
    }
  ]
}
